app/services/unsuspend_account_service.rb

Fix issue #16603 undefined method `serialize_payload' for Unsuspend Account Service error.
It seems that this service forgot to `include Payloadable` so that `serialize_payload` could not be found in this service.
UpstreamPR16605

UpstreamPR16605 service forgot to include Payloadable

---

app.json
config/deploy.rb
lib/mastodon/version.rb
lib/tasks/repo.rake
package.json
spec/presenters/instance_presenter_spec.rb

Change patch version to 9001 so it's clearly out of the normal realm of patch numbers.
Helps with #109 but not a full solution.
Fixes #143

update labeling and version

---

.deepsource.toml

After transferring my repo to c4social, I had to reconfigure deepsource. In that process, they pushed a new toml file to the c4social c4 branch. This reverts that back to the one that matched how upstream applies deepsource

revert deepsource changes

---

README.md

Due to misunderstanding how variables-based links work in markdown the badges to upstream section of readme were broken. This fixes that and also links to a fun badge to be hosted by c4social.org.

Fix badges, add fun one

---

app/javascript/mastodon/features/compose/components/compose_form.js
app/javascript/mastodon/features/compose/containers/compose_form_container.js
app/javascript/mastodon/features/compose/index.js

When opening a page such as /web/timelines/home in a desktop browser, the
cursor was automatically placed in the textarea of the compose form.
When using the keyboard for navigation (using a browser plugin like vimium or
vim vixen, or just to hit 'space' to scroll down a page), you have remember to
leave the field before using that.
Since you only visit the page to write a new post some of the time, this PR
attempts to have nothing focused initially (and require the user to click or
e.g. use 'tab' to focus the textarea).
Tested:
* /web/timeslines/home no longer autofocuses the compose box
* pressing the 'n' hotkey still focuses the compose box
* clicking 'reply' for a post still focuses the compose box
* replying to a CW'ed post still focuses the compose box
* introducing the CW field …

Don't autofocus the compose form

---

app/controllers/admin/export_domain_blocks_controller.rb
config/locales/simple_form.en.yml
spec/controllers/admin/export_domain_blocks_controller_spec.rb
spec/fixtures/files/domain_only_blocks.csv

Issue: #261 
This pr deals with adding a functionality to make sure csvs with just domains are allowed to be imported with certain default values. Further details are commented in the issue itself.

fix: add domain only import functionality (#261)

---

app/controllers/admin/export_domain_blocks_controller.rb
config/locales/simple_form.en.yml

Minor change to domain blocklist defaults to reduce unintended consequences of content removal. This only affects upload of a simplified blocklist.
Also clarifies the text in the UI for blocklist import.
Related to #261

Tune simple domain blocklist defaults, tweak wording in UI

---

lib/mastodon/domains_cli.rb

#262 Add new tootctl command namely tootctl domains import_blocked
commands that can be performed
toolctl domains import_blocked
bin/tootctl domains import_blocked
toolctl domains import_blocked -u different-csv-url
This command can take in -u as the url option if any different url is required to be imported, else it will take the default url, i.e 
https://csv.rathersafe.space/f.php?d=1&h=39IM2DCd which is a list fetched from https://rathersafe.space/fediblock.
This will also add all the domains in a similar manner as the import feature performed for #261. This will also work for the format provided by the export feature.
Since test cases are non existing for these cli features. I have tested them manually and take some screen shot for reference.
This reference below when all the …

feature: add new tootctl command to import urls from a csv url download

---

lib/mastodon/domains_cli.rb

As noted [here](https://github.com/magicstone-dev/ecko/pull/271/files#r752563735) `merge` was never incremented so this PR removes it.
Also improves wording for help text for import_blocks.

Import blocklist CSV: Remove unused variable, improve help text

---

app/helpers/application_helper.rb
app/models/form/admin_settings.rb
app/views/admin/settings/edit.html.haml
config/locales/en.yml

Fixes #245 
This was created from #273 by manually re-applying each relevant changed line.

Allow editing of favicon from the UI (manually rebuilt version)

---

gems/ecko-plugins/lib/ecko/plugins/stripe/rails/routes.rb

Removes pry dependencies which doesnt seem to be in the non development gems.
Docker compose build worked smoothly on my system.

remove pry as a depedencies (#306)

---

app/controllers/settings/static_settings_controller.rb
app/models/account.rb
app/models/static_setting.rb
app/policies/static_settings_policy.rb
app/serializers/initial_state_serializer.rb
app/serializers/rest/instance_serializer.rb
app/validators/poll_validator.rb
app/validators/status_length_validator.rb
app/views/settings/static_settings/index.html.haml
config/routes.rb

This pr will fix the settings issue that was faced. 
Will fix #315 , #297

fix static settings issues and code refactor (#297)

---

docs/INSTALL_DOCKER_COMPOSE.md

While installing another docker-compose setup, ran across this error:
```
$ docker-compose run --rm web bundle exec rake mastodon:setup
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.db.environment contains {"POSTGRES_PASSWORD": "thesecretpassword"}, which is an invalid type, it should be a string
```
This turned out to be a typo where colons were used instead of equals for these config vars.

Fix not a string error by using the proper equals signs

---

app/javascript/mastodon/features/ui/components/navigation_panel.js
app/javascript/mastodon/initial_state.js
app/serializers/initial_state_serializer.rb

This fixes #358. If we donot provide STRIPE_API_KEY and STRIPE_CALLBACK_URL envs, The donate button will not be shown.

donation button not to be shown if envs not provided (#358)

---

lib/mastodon/donations_cli.rb

Fixes #365 
The pk sequence is not indexed correctly. We need to reset it to run it correctly.

fix database pk error while creating package (#365)

---

docs/INSTALL_DOCKER_COMPOSE.md

Solution: Change installation instructions to use `docker-compose pull` instead, if the user is using pre-built images.
Closes #436

Problem: docker-compose build does nothing for pre-built images

---

config/initializers/content_security_policy.rb

Another security fix included in Mastodon's bump to 4.0.2
Commit and discussion: https://github.com/mastodon/mastodon/commit/b46b7c3d5e4e932d61d74418957c824ce7c5f9f7

Use unsafe-wasm-eval in script-src CSP per Mastodon v4.0.2

---

lib/mastodon/accounts_cli.rb

Adds command which deletes accounts that have never interacted with local as well as many avatar/header images. This is tribela's code from https://github.com/mastodon/mastodon/pull/18397
The command is `tootctl accounts prune`
Related: #446

Add tootctl accounts prune

---

app/javascript/styles/mastodon/components.scss

Related: #447
Tested on local with `@corvina@qoto.org` profile.

Stop text on long toots from overflowing

---

Gemfile
Gemfile.lock

Creating this manually to see if there's any difference as to CI passing.

Bump devise-two-factor from 4.0.1 to 4.0.2

---

app/controllers/concerns/signature_verification.rb
app/helpers/jsonld_helper.rb
app/lib/activitypub/activity.rb
app/lib/activitypub/linked_data_signature.rb
app/services/activitypub/fetch_remote_account_service.rb
app/services/activitypub/fetch_remote_key_service.rb
app/services/activitypub/fetch_remote_status_service.rb
app/services/activitypub/process_account_service.rb
app/services/fetch_resource_service.rb
spec/services/activitypub/fetch_remote_account_service_spec.rb
spec/services/fetch_resource_service_spec.rb

This is a port of the fixes released today for Mastodon (see https://mastodon.social/@MastodonEngineering/111839553542311522)
Due to the severity of the issue, we recommend you merge this patch ASAP.
Please be aware that I only performed cursory verification of the patch's correct behavior, so I encourage you to take your time to review it carefully once it is deployed.
Finally, please understand that we do not officially support older versions (see https://github.com/mastodon/mastodon/blob/main/SECURITY.md for officially supported versions) nor forks, and while I exceptionally ported this patch, I am not able to ensure this will happen for any other patch going forward.

Fix insufficient origin validation
