- Vagrantfile
> replace keys.gnupg.net with curl from rvm.io

- README.md
> Add fork description and update some shields

- app/javascript/mastodon/components/attachment_list.js
> ClearlyClaire fixes attachment no url

- app/javascript/styles/mastodon/components.scss
> ClearlyClaire fixes download button color in audio player

- app/javascript/mastodon/features/compose/containers/navigation_container.js
- app/javascript/mastodon/features/compose/index.js
- app/javascript/mastodon/features/ui/components/confirmation_modal.js
- app/javascript/mastodon/features/ui/components/link_footer.js
> Fedibird fix logout link not working in safari

- README.md
> remove last sync'd date from readme

- docker-compose.yml
> point to c4 docker image

- README.md
> Update svgs and links in readme to post-transfer location

- app.json
- config/deploy.rb
- lib/mastodon/version.rb
- lib/tasks/repo.rake
- package.json
- spec/presenters/instance_presenter_spec.rb
> Switch weex to c4social for repo links, main branch too

- .env.production.sample
- app/javascript/mastodon/features/compose/components/compose_form.js
- app/javascript/mastodon/initial_state.js
- app/serializers/initial_state_serializer.rb
- app/serializers/rest/instance_serializer.rb
- app/validators/status_length_validator.rb
apply changes from hometown#40 to help with #122
> Make post-length editable by config file

- README.md
> Update README to solve a few minor issues

- .env.production.sample
- app/validators/poll_validator.rb
Apply glitch-soc/mastodon/1488  to fix #221
> add poll options ENV var

- app/javascript/mastodon/reducers/compose.js
> change poll default to three days

- config/locales/en.yml
> Replace "in due time"

- DEMO_SERVER_SETUP.md
- README.md
- db/seeds.rb
- demo/data_cleanup_scheduler.rb
- demo/sidekiq.yml
This pull deals with adding docs for setup of demo server. This will help setting up demo server by performing three steps. 1. Disable Registration, Stop email sending process and cleanup data every 24 hours.
> Add Demo setup Readme file

- config/locales/en.yml
- config/locales/en_GB.yml
The simplest of approach. Changes from Mastodon to Ecko
> fix: update from mastodon to Ecko (#259)

- app/controllers/settings/base_controller.rb
- app/controllers/settings/static_settings_controller.rb
- app/models/account.rb
- app/models/static_setting.rb
- app/policies/static_settings_policy.rb
- app/validators/poll_validator.rb
- app/validators/status_length_validator.rb
- app/views/settings/static_settings/show.html.haml
- config/navigation.rb
- config/routes.rb
- db/migrate/20211130104215_create_static_settings.rb
- db/schema.rb
> UI for env variables

- app/models/static_setting.rb
> Change sanity check to 5k chars

- Dockerfile
> fix: add copy command early to get gems into the container

- app/javascript/mastodon/features/compose/components/poll_form.js
- app/javascript/mastodon/initial_state.js
- app/serializers/initial_state_serializer.rb
> fix max_poll_options and max_poll_option_chars values

- CODE_OF_CONDUCT.md
- README.md
- docs/DEMO_SERVER_SETUP.md
- docs/INSTALL.md
- docs/INSTALL_DOCKER_COMPOSE.md
General establishment of docs folder.
Also fixing #275
> Create install docs and docs/ directory

- lib/mastodon/domains_cli.rb
command: bin/tootctl domains:export_blocked <url>
Need testing on a real time senario.
> add new tooctl command to export domain block list (#316)

- gems/ecko-plugins/ecko-plugins.gemspec
Remove git dependencies from the gem as spec is on the way currently.
> remove git dependencies from gemspec (#329)

- lib/mastodon/domains_cli.rb
Fix #322, The headers were not checked correct and #serverity was also being created.
> fix domains with headers (#322)

- db/migrate/20211219013911_add_sponsor_and_donation_to_accounts.rb
> Change default after add as suggested by migration process

- lib/mastodon/donations_cli.rb
> remove url from description

- gems/ecko-plugins-sponsor/lib/ecko/plugins/sponsor/parser/stripe.rb
- gems/ecko-plugins-stripe/lib/ecko/plugins/stripe/checkout.rb
> configure based on what to show in the button (#349)

- app/models/donation_package.rb
- lib/mastodon/donations_cli.rb
This adds feature mentioned in #347 
You can add by:
Add new package
RAILS_ENV=development bin/tootctl donations create_package <title> <amount> <desc>
Remove new package
RAILS_ENV=development bin/tootctl donations remove_package <title>
Can find more options in lib/mastodon/donations_cli.rb
> add cli to add and remove donation package (#347)

- app/javascript/styles/fairy-floss.scss
- app/javascript/styles/fairy-floss/diff.scss
- app/javascript/styles/fairy-floss/variables.scss
- app/javascript/styles/macaron.scss
- app/javascript/styles/macaron/diff.scss
- app/javascript/styles/macaron/variables.scss
- app/javascript/styles/merveilles-dark.scss
- app/javascript/styles/niboe-oscuro.scss
- app/javascript/styles/witches-colors.scss
- config/locales/en.yml
- config/themes.yml
> Add five themes

- lib/mastodon/donations_cli.rb
The donations CLI didn't have much help text so this adds it and updates some of the wording so it's easier for a new admin to understand.
> Update wording, add more usage info

- app/javascript/mastodon/components/sponsor.js
- app/javascript/styles/mastodon/components.scss
Fixes badge UI. Adds functionality for emojis. #357
> add emoji for badges (#357)

- lib/mastodon/donations_cli.rb
Helps with #374
Tested locally to allow sidekiq to come up and that create_package works.
> Wrap arguments as hash

- Dockerfile
- Gemfile
- Gemfile.lock
- docker-compose.yml
This issue actually tries to solve docker compose issue. Please dont merge this before testing.
Here there are two things to keep in mind. We might need to update docker-compose file image value after testing. 
The ruby version will be bumped to 3.0.3 from 2.7.4. It should not hamper much since the CI/CD validates that the repo works with ruby  3 as well.
> fix docker compose fail

- app/models/status.rb
- db/migrate/20220116082923_add_content_type_to_statuses.rb
- db/schema.rb
Remove default value for migration.
> remove default value for content type (#390)

- app/javascript/styles/undescribed-subtle.scss
- app/javascript/styles/undescribed.scss
- config/locales/en.yml
- config/themes.yml
> Add highlight undescribed media themes

- app/controllers/api/v1/statuses_controller.rb
> Default content_type to text/plain

- app/javascript/mastodon/features/compose/components/compose_form.js
- app/javascript/mastodon/features/compose/components/privacy_dropdown.js
- app/javascript/mastodon/features/compose/containers/privacy_dropdown_container.js
Shift federation dropdown to visibility dropdown. Helps with #340
> update federation dropdown (#340)

- README.md
Added link to https://rfc.zeromq.org/spec/42/. May need more accessible elaboration.
> Problem: README does not elaborate on C4 protocol.

- app/javascript/mastodon/features/emoji/__tests__/emoji-test.js
- app/javascript/mastodon/features/emoji/emoji.js
- app/lib/formatter.rb
- config/initializers/rack_attack.rb
- config/routes.rb
Fixes rate limiting for paths with formats
> apply security fix from v4 Mastodon

- .circleci/config.yml
> update docker images to cimg namespace

- .circleci/config.yml
> Update CircleCI from upstream
